FROM node:20-slim AS build
ARG VITE_API_BASE_URL
ARG VITE_MIX_PUSHER_APP_KEY
ARG VITE_MIX_PUSHER_APP_CLUSTER
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_MIX_PUSHER_APP_KEY=${VITE_MIX_PUSHER_APP_KEY}
ENV VITE_MIX_PUSHER_APP_CLUSTER=${VITE_MIX_PUSHER_APP_CLUSTER}
WORKDIR /app
COPY . .
RUN yarn
RUN yarn run build

FROM node:20-slim AS prod
WORKDIR /app
COPY --from=build /app .
EXPOSE 5000 8080 4173
CMD ["yarn", "preview", "--host", "0.0.0.0"]
